---
tap_install:
  secrets:
    eso:
      aws:
        region: us-west-2
        tap_install_secrets:
          role_arn: arn:aws:iam::375783000519:role/ra-tap-view--tap-install-secrets
      remote_refs:
        tap_gui_cert:
          tls_crt:
            key: dev/ra-tap-view/tap/tap-gui-cert-values
            property: tls.crt
          tls_key:
            key: dev/ra-tap-view/tap/tap-gui-cert-values
            property: tls.key