apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: deliverables
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  fetch:
  - git:
      url: ssh://git@github.com/pakiheart/tap-gitops-deliverable.git
      ref: origin/main
      secretRef: 
        name: sync-git-ssh
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          update-branch.yml: |
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"kind":"Deliverable"})
            ---
            spec:
              source:
                git:
                  ref:
                    branch: prod   
  deploy:
  - kapp:
      rawOptions:
      - --dangerous-override-ownership-of-existing-resources=true
      - --dangerous-allow-empty-list-of-resources=true
      - --diff-changes=true















