#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-gui-cert
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: eso/tap-gui-cert
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/secretstore"
spec:
  secretStoreRef:
    name: tap-install-secrets
    kind: SecretStore
  refreshInterval: "1m"
  target:
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tls_crt | b64dec }}"
        tls.key: "{{ .tls_key | b64dec }}"

  data:
    - secretKey: tls_crt
      remoteRef:  #@ data.values.tap_install.secrets.eso.remote_refs.tap_gui_cert.tls_crt
    - secretKey: tls_key
      remoteRef: #@ data.values.tap_install.secrets.eso.remote_refs.tap_gui_cert.tls_key
