#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tap-gui-cert-store
  namespace: default
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: #@ data.values.tap_install.secrets.eso.aws.region
      auth:
        jwt:
          serviceAccountRef:
            name: tap-gui-cert-store
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: #@ data.values.tap_install.secrets.eso.aws.tap_install_secrets.role_arn
  name: tap-gui-cert-store
  namespace: default
